<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>StardewValleyAssistantNpcLocations</AssemblyName>
    <RootNamespace>StardewValleyAssistantNpcLocations</RootNamespace>
    <TargetFramework>net6.0</TargetFramework>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <CopyToGameFolder>false</CopyToGameFolder>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="E:\Codes\Web\stardew-valley-source\SMAPI\src\SMAPI\SMAPI.csproj" Private="False" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="MonoGame.Framework" HintPath="$(GamePath)\MonoGame.Framework.dll" Private="False" />
    <Reference Include="Stardew Valley" HintPath="$(GamePath)\Stardew Valley.dll" Private="False" />
    <Reference Include="StardewValley.GameData" HintPath="$(GamePath)\StardewValley.GameData.dll" Private="False" />
    <Reference Include="xTile" HintPath="$(GamePath)\xTile.dll" Private="False" />
  </ItemGroup>

  <ItemGroup>
    <None Update="manifest.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
