// Barrel import — triggers all widget registrations
import "./weather-forecast"
import "./coins"
import "./farm-level"
import "./friendship-progress"
import "./perfection"
import "./collection-progress"
import "./farm-overview"
import "./skills-overview"
import "./friendship-summary"
import "./game-time"
import "./real-time-clock"
import "./custom-image"
